application:
    build: ../back-end
    volumes:
        - ../back-end:/var/www
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        - ./php-fpm/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
        - ./php-fpm/symfony.pool.conf:/etc/php5/fpm/pool.d/symfony.pool.conf
    links:
        - db

client:
    build: ../front-end
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/client.conf:/etc/nginx/conf.d/default.conf
    links:
        - nginx-back

db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony

nginx-front:
    image: nginx
    ports:
        - 8080:8080
    links:
        - client
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/express.conf:/etc/nginx/conf.d/default.conf

nginx-back:
    image: nginx
    ports:
        - 8090:8080
    links:
        - application
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
